# https://taskfile.dev

version: "2"

tasks:
  build-client:
    cmds:
      - mkdir release || true
      - go build -o release/bottle-cli ./cmd/client
  build-server:
    cmds:
      - mkdir release || true
      - go build -o release/crate ./cmd/server
  build:
    cmds:
      - task: build-server
      - task: build-client
  test:
    cmds:
      - golangci-lint run
      - go test -v ./...
  sonar:
    cmds:
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN
